### ISSUE TITLE
General Problems

### ISSUE THREAD

**Issue by SteffenGorenflo** [HTWG-VirtualReality/prototyp#1]
- live rezising
- text eingabe
- angriffspunkte + aktionen (verschieben, rotieren, etc...)
- kamera wechseln
- verbindung von elementen (live)
- neue elemente hinzufügen (aus palette auswählen)
- Klassendiagramm erstellen

**Comment by T1m1** [comment]
**Text Eingabe**
_Prototyp_: http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage

_Alternativen_
- Spracheingabe ( https://cloud.google.com/speech/ )
- LeapMotion ( https://www.youtube.com/watch?v=ZERwYJVZOgk ---- https://www.youtube.com/watch?time_continue=37&v=t5Fg8xrzbvY )
- Ganz komische Eingabe ( https://www.youtube.com/watch?v=FFQgluUwV2U )
- Touchpad (mit Bluethooth) ( https://www.youtube.com/watch?v=lgEIjZtg4Go )
