### ISSUE TITLE
Create different connection types for class diagram

### ISSUE THREAD

**Issue by T1m1** [HTWG-VirtualReality/prototyp#17]
e.g.
- composition
- extends
- implements
  ...
- dashed line

Different end's in line element

**Comment by magoeke** [comment]
Picture of different connection types
https://en.wikipedia.org/wiki/Class_diagram#/media/File:Uml_classes_en.svg

**Comment by magoeke** [comment]
Most connection types are implemented. To get the other types you need to modify the existing ones(no big modification).
