### ISSUE TITLE
Build example uml diagram with all components

### ISSUE THREAD

**Issue by T1m1** [HTWG-VirtualReality/prototyp#23]
**Example**
![image](https://cloud.githubusercontent.com/assets/5616884/15257573/3fef8b5c-1947-11e6-932f-e1b5fa0babd8.png)

**Comment by T1m1** [comment]
![image](https://cloud.githubusercontent.com/assets/5616884/15453961/8648f310-202a-11e6-8956-073adc69d7bc.png)

**Comment by magoeke** [comment]
Added connections in commit: aea48962a212309de019079ac8a554cd5fa66320
