### ISSUE TITLE
Delete element by mouse

### ISSUE THREAD

**Issue by phaldan** [HTWG-VirtualReality/prototyp#42]
Create new behaviour for vr-class to delete polymer and three.js element.
Button for delete reveals after click on vr-class and another click on the button executes deletion.

**Comment by magoeke** [comment]
Bug: Class is not selected and delete button not visible but if you click on the space where the button is it deletes the element.

First tried solution - Add Highlighted flag to class: Class doesn't get deleted but it's getting selected.

**Comment by magoeke** [comment]
Finished. It only needs some frontend love. @T1m1 can you do this? You already embedded some pictures
