### ISSUE TITLE
Implement sizeMax and sizeMin for every Shape Element

### ISSUE THREAD

**Issue by SteffenGorenflo** [HTWG-VirtualReality/prototyp#58]
according to the zeta grammer, each shape element has the property sizeMin and sizeMax (in width and height) to prevent elements getting to big or to small because of possible subelements.

**Comment by phaldan** [comment]
Extend Size behaviour with new html-attributes:
* max-height (disabled by default: -1)
* max-width (disabled by default: -1)

**Example:**
```
<vr-ellipse width="20" height="20" max-width="50" max-height="50"></vr-ellipse>
```
