### ISSUE TITLE
Implement resizing property

### ISSUE THREAD

**Issue by SteffenGorenflo** [HTWG-VirtualReality/prototyp#59]
It should be possible to allow/disallow the resizing of an element in either horizontal or vertical direction.

Furthermore should it be possible to resize proportionally to its parent element

**Comment by phaldan** [comment]
Extend Resize behaviour with two new html-attributes:
* resize-horizontal (enabled by default: 1)
* resize-horizontal (enabled by default: 1)

**Resize disabled:**
```
<vr-ellipse resize-horizontal="0" resize-vertical="0"></vr-ellipse>
```
