### ISSUE TITLE
Extract image and text of vr-box to behaviours

### ISSUE THREAD

**Issue by phaldan** [HTWG-VirtualReality/prototyp#71]

**Comment by magoeke** [comment]
It'd be nice if the image behavior also works for every element not only vr-box.

Maybe you can use the vr-text element for texts?

**Comment by phaldan** [comment]
I have added a new FrontSide behaviour with a registerFrontSide(...) method. Text and Image behaviour will inherit from this behaviour. With this approach the polymer element can tell the behaviours which THREE.MeshBasicMaterial is the front facing one.
